# fly.toml app configuration file generated for avp on 2023-08-05T14:33:58+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "avp"
primary_region = "bos"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
